### ISSUE TITLE
建议把被删贴时间模糊处理

### ISSUE THREAD

**Issue by pdnywl** [AowuCat/PKUHoleRecorder#1]

**Comment by AowuCat** [comment]
感谢您的关注。

当前的被删帖时间已经有10 min量级的误差。
请问一下，“模糊”是要什么程度呢？以及这样做的理由？

**Comment by pdnywl** [comment]
如果你的删帖时间是请求 getone / getcomment 报404的时间，`access.log` 会瞬间暴露行踪。
如果是 getlist 的话，几个数据点就能锁定你了

**Comment by AowuCat** [comment]
我没有使用getone / getcomment，且getlist的频率很低。
在没有大量账号的情况下，要想不被锁定应该相当困难。可能只能降低更新的频率了。
或许改成一天一更？

**Comment by AowuCat** [comment]
不好意思，我才明白你的意思。尽快修改，感谢。

**Comment by pdnywl** [comment]
嗯嗯不客气，也可以把issue删了，否则getlist:getcomment比例异常被发现了也是个大flag
