### ISSUE TITLE
开个贴聊下天吧

### ISSUE THREAD

**Issue by pdnywl** [AowuCat/PKUHoleRecorder#2]
对项目停更表示遗憾。

不知道为啥突然官方树洞动作频频，十一的时候关了一大批不在校账户，现在又是触发captcha。
根据测试，貌似captcha是挂在 `getcomment` 下的，因此其实不直接影响这个项目。所以特意过来看了一眼，可惜还是停更了。
的确风险很大，而且惊讶的是helper团队置用户体验于不顾，强力推出反爬措施。

**Comment by AowuCat** [comment]
是的，在挂出置顶后很长一段时间内项目仍然正常运行。
可能是有别人高频率爬树洞引起了注意？据我观察前两天那个自动填报出入校的团队就暗示要爬树洞。
在没有大量账号的情况下，连我这种业余选手都有一百种办法可以轻松确定我的身份，唉。

**Comment by pdnywl** [comment]
很有可能
最近怨声载道，可能有人要爬树洞直接搬到鸿蒙去吧。。。

最近很多爬虫都相继失效了，我知道的几个token池基本都废了。除了有个电报群，基本上不剩其他项目了。树洞💊

**Comment by AowuCat** [comment]
药丸。可惜鸿蒙那边人气很低，也不知道他们有什么办法还是就佛了。

**Comment by AowuCat** [comment]
对了上周树洞还有一个小更新，原来getlist能翻99页，更新后只能翻20页了。开学后树洞人气走高，就算99页都爬不满当天的。

**Comment by pdnywl** [comment]
惋惜，helper做的这么烂，出现竞争者只管删帖禁止传播就可以了，根本不需要开发新功能。现有用户的优势被利用到极致了。

getlist的确是限流了。search最近也有动作。很可能是针对某个爬虫的特征，量身定制的一套安全措施。。。

**Comment by AowuCat** [comment]
我也觉得。就我这小透明，一般半分钟闲时五到十分钟一次的刷新频率，犯不着挂个置顶针对我。。

**Comment by pdnywl** [comment]
搞不好是新政策

鸿蒙也不知道会怎么样，就这封杀力度，大概率要凉

**Comment by AowuCat** [comment]
话说现在还有别的备份项目活跃吗？
比如telegram上那个？

**Comment by pdnywl** [comment]
WhatDoZhaosFear 延迟很高也是被搞得最狠的
现在是工作的应该

**Comment by pdnywl** [comment]
我记得那个群的开发者还被helper团队实名挂过

**Comment by AowuCat** [comment]
挺晚啦，先聊到这吧。感谢大佬对本项目的关注！
话说这个楼是留着还是炸了？

**Comment by pdnywl** [comment]
过奖了

我不介意留着，考虑到也许有其他大佬愿意分享技巧，听你的

**Comment by AowuCat** [comment]
那留着吧，晚安-w-

**Comment by AowuCat** [comment]
您还在吗，来聊聊天吧

**Comment by pdnywl** [comment]
我在，我们交换一下public key吧

```
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCyovYGERXhuWsgKIFTUAhZAdHv
DljyV0auJUNmDcjamGQjPIryg6BoKyVS9v1WuEPFIrwz0qqL0yPgda/L/mGdgLQy
VVsq8rn3TGJn4zvIklBkLGbOUwMIS8KTXQ+BgdvGMy852mH4LW1kgXZsf2KGg6l+
xwx7U0MmRRHEvbxhiwIDAQAB
-----END PUBLIC KEY-----
```

**Comment by AowuCat** [comment]
`AAAAB3NzaC1yc2EAAAADAQABAAABAQDlIoftwy0I5ahkM9c1qMC54+5r1bIA7IM/1/Y0ZIQHBkcMjbanSA5+NS6qQXaLPHTVaFMy8oHxn1CBraeZ3aW/xQreLspWhwloV87Ew5iO/h5ueb/Q1jGp3CTl+q0hZ0e7AKpJA5WO4poLVVqZg9JRrpCs3E/MvS4wwjB5jEaH2lqg+3oNzFq8/KXquufKJ7GE1mbtelgDvl0TqG/MbOFv2AsQqXhqMW/vvFT7hud2ac8FHzjRTIZJ65e+jv50OlaqIsbcgQMiSEc6Wcs6iF7jkWGoxM21lGcAveRlpelN5+8swlQAhucCz07RRmVFI8JbTWomi5y8p1utql0xF2Bl 
`

**Comment by AowuCat** [comment]
> MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCyovYGERXhuWsgKIFTUAhZAdHv
DljyV0auJUNmDcjamGQjPIryg6BoKyVS9v1WuEPFIrwz0qqL0yPgda/L/mGdgLQy
VVsq8rn3TGJn4zvIklBkLGbOUwMIS8KTXQ+BgdvGMy852mH4LW1kgXZsf2KGg6l+
xwx7U0MmRRHEvbxhiwIDAQAB

**Comment by AowuCat** [comment]
`ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDlIoftwy0I5ahkM9c1qMC54+5r1bIA7IM/1/Y0ZIQHBkcMjbanSA5+NS6qQXaLPHTVaFMy8oHxn1CBraeZ3aW/xQreLspWhwloV87Ew5iO/h5ueb/Q1jGp3CTl+q0hZ0e7AKpJA5WO4poLVVqZg9JRrpCs3E/MvS4wwjB5jEaH2lqg+3oNzFq8/KXquufKJ7GE1mbtelgDvl0TqG/MbOFv2AsQqXhqMW/vvFT7hud2ac8FHzjRTIZJ65e+jv50OlaqIsbcgQMiSEc6Wcs6iF7jkWGoxM21lGcAveRlpelN5+8swlQAhucCz07RRmVFI8JbTWomi5y8p1utql0xF2Bl 
`
这次好了！

**Comment by pdnywl** [comment]
好像不行，试一下https://www.devglan.com/online-tools/rsa-encryption-decryption？你发的第二个我能用

**Comment by AowuCat** [comment]
都没用过，十分不熟练，让您见笑了。。
让我学习一小下！

**Comment by pdnywl** [comment]
没事。。我也是网上现找的，这招还是从清华树洞学来的

**Comment by AowuCat** [comment]
> -----BEGIN PGP PUBLIC KEY BLOCK-----
>mQINBF+gNKUBEACoYSBRsKHxBBrtQ5eYlDh+hKWiSMJCR71awICjuLWXgqgMt4dZ
Uk73tT6bZuolPBHhCgAZAzXZJXze2Tn2qbmdiFkzYyq0tdqYAD7rESD6TD9/DZ41
etr7Y2LptygglumKT+miOo43rSz9f9U+DQscbbxIslqH/ajB00n4EvVCactibevG
+P8zvIL8shbCnlQSuSkyD3cqf0OYOTkx8tNxtHjKoZrwed8XcPm/5HhgR8vMExcm
roogYbfZl7lZOOCowpEGOPuYSvH88OC4IQCG2uYJ/5tknpNFqCLXI8Mr47QzYaof
PTI9AMi8+JCpvtOx2W9ua0/qB5tMLHdmBI+o58BNdNjo7lgiRZh06G7ItmXuON59
jA1onqsLRc9cvgeZLnyXFNbBqd3774NgW7RQ8QYcwd2mTCLgei9eQMi/yJyChtsl
O+w3wTLLwkcelBeUigoOImJc/B0Yz2UGJGGx7XY7YkCZKdWRcaEWx0dk+DzM9Oes
vwdDrMuAYUPYloRnpqk04aPceGnMb8ccBa68lVCTi7TgLJEwS8KIGV+hqmI6nn8e
c4UiFhTJOyYczSkx+XWXO7r79igWCCs7jr/anKi3zwQtpFXMMikZJFqhBvsNlLg7
ZUGH7t02LHTxCxPNDyivUz93FMuB3kAnZC6Y1yzv9UYsDaXdX5gScUvtnwARAQAB
tAdBb3d1Q2F0iQJOBBMBCgA4FiEENH75oDgMZ9u+Ge8Qq5KDmpZJv2AFAl+gNKUC
GwMFCwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQq5KDmpZJv2DqGRAAha90pMpj
DGa0n4thlXHtAWAsa9S40rYCB8Reen9Ty/V/Xdp7h2UA2iO3FADhgqqaXfDudLOI
zcRVZnpu3WcUBZbNCU/oMTKgT8xg4A+BBct/fRsz3xua1NJ1o0c7NfRLaq1On7zF
Qt1vc2lUCDHOIpYknRSAesTQQdhRd6NPBCVW1GK6WE2rno8SlAdHmVWHl31/b+gC
yRawVSdixzg1J+Yk3UCrhUQKEF4XE0wqvCKNBH/zWYQAlJLQfJI2+wn1wGHzlZgI
RY7cHH30iSH2PfJtBRKwBKj9jVo2x+0rf+Zh3wouQNTmbLSWkdEaAOY5RVsurSTC
KN7LCBwtIygBlCBOIxOjEOfOmNI/UinbaATf33dsSyY9jhtXefZRjOhkcYdlIY7r
Ywcxot2JwK1TvNBrKYRXysiv2Jd9ioxjAWqoSEej2apk6D6xLGei1iy+9C4CnFuV
GfwweEExe3c+8kDx2u7HAsEGI8hzt96+hO864Yy/0KGUNdaaceYAWdhwtSAUUX0W
Sx552sK9+ZD07xYniussg0moBbLjq/AM4f7EfkUkMGc0tByb4j2fa0LV5RX2Qiy+
RRvl2Tbp+DT280jqcw1U8JoWyX8cztM7TwLTVw72CFgWSU/H0V/lsKjlmpI+w5lC
Fopoqo7agLRAGcTRm+j3Z6CpwlHYfxxs8BW5Ag0EX6A0pQEQAOILGzzx4lLzLZm0
o8nhvWdWBRXI8c0BT5v1fbcZTevSfbrSyT3x0Hv10Sup0eMqj6+4AZbRsMj6PODb
P8AtlWP91mAwFKbJimgDhPC2qPgl/CObdwx3QJKsRKUq/CBiQnvIafBPBDOClEy4
wnX3+vCRvPJpbBE00Pf2YkfhGBxMiEKRBcAt/WUIvM/FS0ng3zf80nVTdCip7yN5
1FFY3v0m5+sARss4kqddR4fRmYGijxGvexlgb4dQJ+aQnQba4dMYZiCPmG7AkSd+
EiVNebf+g4cew9acpOULTFi7Ft7k7Dh4UhyMrv0hb6BKyNzUy55/px94sJBjscis
gOGZPG4YYsWrFxFnGVyKAWKAo8d/I09kZcRMuF2OyYgle6ZSMwI+oQbC590r6XdM
Rv7qBSyDvZ89tcEg9zD+47V1jkZ/3HIolggviS+09QkzZu1EBa0q3JVFpc884Gs6
WfgB42/h/aojZqURMY84GoCz0d80VsFd6nh0yk+0x2LBkDmVVBSoDqVjsHnwym/1
MDvrpr0hotnWlSVqfySD9eJ5dt3ze2ljy0E66ualZOP2TRoc0KhxvXxs/W0V2Pns
7UArr+Y+7hHNYN5rFQk/DuOkurTbCBoo3Q3Wch80EwOTg/z6s+tyLkvug8UWrhpZ
exYMpCYfg5Z3JRyrqHww2K+LTMOvABEBAAGJAjYEGAEKACAWIQQ0fvmgOAxn274Z
7xCrkoOalkm/YAUCX6A0pQIbDAAKCRCrkoOalkm/YDtfD/9RSdU82N7+G5/x+7Tl
OHHqGGxp1FHfGj9kb/cjO5yWY2g0hjwTMkC1q/PVY9uitTdCve/tGCVrM1PJPZK7
NO9LRSiuGu2bNipMaZc7Fp01+CZtkoeMWRz9plepWFhtlVnAyjStV4jDFwE+k2UT
BPGTKSMWVYexAulzF299QemzS20EvGgfEqM0uL6YHAOepGRzT89jb/EQQAnPKDtu
/kjOSdFQs6wEqG4l0AnttQ9NPyR6ZeAmgLExBqle02KA4Y+PEGgZj1fUkQlSWUxw
Drrr0OP+sCGROkcaNXCYbmp3WqtSq3jRxxJtX+k+RQ8Nu6ma9jtdmR3tn1QHsDQj
JJiNn5vuB7e9Jul94uIHPkemJIMph8wF2FRArlCsXDnP2P6RWEsQCIgsnBT5kaOO
LVDLSIdvlA8pleuqgzDoieDbbuSBu+3dvD24pJw5aaoWKElwe0DaCaK2C5jNqWN6
CrzmMdZrlupvhz3y3GYpqADvgRD3mdI/JDTCitusPioRDITUrku1DY5t+Buevux+
37wJ0EZ2gPmQ7yeEwC1diTgqmwf4/tGNSltyAJsfouss4lFiyZaKT+b7ydbU7isv
ZaB3GFKDad8Zj100YCtx6yOTYIy+EMExsTvvIbs6BBKcMvb5wWHpbmlB3D1R1e9A
Z+qJUFt2g6gXfBub/1XwhkvhhQ==
=kEiX
>-----END PGP PUBLIC KEY BLOCK-----


这次真的学会了！

**Comment by AowuCat** [comment]
我主要想问问新树洞为什么挂了，什么时候能修好，开发者有事没事……

**Comment by pdnywl** [comment]
```-----BEGIN PGP MESSAGE-----

hQIMA/ec0ztVxCgdARAAuHWOr/ZXHcZZpNtnFRCA6bWkYTrk3rPbse/ehNAbSmqh
1a5CiwQbYnSt8lckxSmrfVL19XCxwlo6L+ET7flRHbgp9j/54RGoCQGDQFMvR/Ak
Jc4p4pABaEEHlvnxzk+IKntPY/waqZpVJJ66mwHN0KXWNah/2HKZXY9TlpjPndeG
chUUNmDjfz6+HqxtXDy/fgOk42pweUzDdsEMH5V3jADcX2n9io+cQ4+mJJ8LlcjS
WQ2ADE++4fNYBJ0sZ/Pt9XGAeQqWrZUAYJMbZ/hsUJXipoDvi8YUEO6QXEOdZhsm
R7z/At4ccGyeF7tDM7OiUc++C2cDHE0H4r71cSQ8pWO45Dlawn2Gc8j+j45fNt6A
7zlZmqkeNjnnqvvBOokBXSH41hf3Oq+XXul4w+IKvhyZJFTPbSmP8NxlkioPDbdG
JAgnHL93rkoLFoQdg4xHN7Bt5CtQd3hzHsJCYnfI4154OZFohO3ylyfQ/uc2tArk
R6a85hDZa4bHcYZBhjRASMUTczGfHWzHAH6vLZvuiGwwXHQUkygfSOURydHOOAHB
9YmwXa3iTK0LjVdmMkVw4W/i5l6KBJprgs5n4J/3d2fqvGivBhNs33Vn7YxusdMQ
NVkj49rZZGHxToYcU5p/201XOKk3xqfcIzw100J4qMI517u7XMaZKCUNGYv1Zi/S
aAGVvXO/0Y1INTyh6uQIT2K/Hati7p0vUzELXPZ3pPig770znP5FeFbClobOhsDf
xw+cWf7D/XsHi6sBvCE8SlLQAhwa9Zh2smthUOAlb8la0ksmi8MmNRzcHg4y9hl5
RvCXVbo+Fjjo
=+a5y
-----END PGP MESSAGE-----```

**Comment by AowuCat** [comment]
> MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCyovYGERXhuWsgKIFTUAhZAdHv
DljyV0auJUNmDcjamGQjPIryg6BoKyVS9v1WuEPFIrwz0qqL0yPgda/L/mGdgLQy
VVsq8rn3TGJn4zvIklBkLGbOUwMIS8KTXQ+BgdvGMy852mH4LW1kgXZsf2KGg6l+
xwx7U0MmRRHEvbxhiwIDAQAB
